#!/usr/bin/env bash
# deploy/box/lib.sh — shared pieces of the box runner (sourced by install.sh and update.sh).
#
# A box is one directory (BOX_DIR, default /opt/onderling) holding:
#   box.conf      the profile: which repos, which roles, which hostnames (shell-sourceable KEY=VALUE)
#   .env          secrets + hostnames for docker compose; never written by update.sh
#   state.json    what is RUNNING: per repo the sha + tag + when — the answer to "what are testers on?"
#   HOLD          present = update.sh does nothing (freeze the box during a walk)
#   repos/<name>  one git checkout per repo, detached at the release branch's sha
#   data/         volumes + the generated Caddyfile
#   box.log       one line per event
#
# The role contract a repo honours (so the feedback repo — or a partner's — plugs in the same way):
#   deploy/roles/<role>.yml      a docker compose fragment; its build contexts are relative to the file
#   deploy/roles/<role>.health   optional executable: exit 0 = healthy; gets the box env + COMPOSE
#   deploy/roles/<role>.caddy    optional Caddy site snippet; ${VARS} are substituted from .env

set -u

BOX_DIR="${BOX_DIR:-/opt/onderling}"
DOCKER="${DOCKER:-docker}"          # tests point this at a fake
GIT="${GIT:-git}"
CURL="${CURL:-curl}"
COMPOSE_PROJECT="${COMPOSE_PROJECT:-onderling}"

log() { printf '%s %s\n' "$(date -u +%FT%TZ)" "$*" | tee -a "$BOX_DIR/box.log" >&2; }
die() { log "ERROR: $*"; exit 1; }

load_conf() {
  [ -f "$BOX_DIR/box.conf" ] || die "no $BOX_DIR/box.conf — run install.sh first"
  # shellcheck disable=SC1090
  . "$BOX_DIR/box.conf"
  : "${REPOS:?box.conf: REPOS is required (name=url#branch …)}"
  : "${ROLES:?box.conf: ROLES is required (role@repo …)}"
}

# REPOS="canopy-mono=git@github.com:Onderling/basis.git#live feedback=…#live"
repo_names() { for r in $REPOS; do echo "${r%%=*}"; done; }
# every lookup ends with `return 0`: callers run under set -e inside $(…), and a non-matching last
# iteration must not read as a failure
repo_url()   { for r in $REPOS; do [ "${r%%=*}" = "$1" ] && { local rest="${r#*=}"; echo "${rest%%#*}"; }; done; return 0; }
repo_branch(){ for r in $REPOS; do [ "${r%%=*}" = "$1" ] && { local rest="${r#*=}"; echo "${rest#*#}"; }; done; return 0; }
repo_dir()   { echo "$BOX_DIR/repos/$1"; }

# ROLES="caddy@canopy-mono relay@canopy-mono feedback-collect@feedback"
role_names() { for r in $ROLES; do echo "${r%%@*}"; done; }
role_repo()  { for r in $ROLES; do [ "${r%%@*}" = "$1" ] && echo "${r#*@}"; done; return 0; }
role_file()  { echo "$(repo_dir "$(role_repo "$1")")/deploy/roles/$1.$2"; }
roles_of_repo() { for r in $ROLES; do [ "${r#*@}" = "$1" ] && echo "${r%%@*}"; done; return 0; }

# The compose command for every enabled role: one project, one env file, N fragments.
compose_cmd() {
  local cmd=("$DOCKER" compose --project-name "$COMPOSE_PROJECT" --env-file "$BOX_DIR/.env")
  local role
  for role in $(role_names); do
    local f; f="$(role_file "$role" yml)"
    [ -f "$f" ] || die "role $role: $f missing (does $(role_repo "$role") honour the role contract?)"
    cmd+=(-f "$f")
  done
  printf '%q ' "${cmd[@]}"
}

# Render data/caddy/Caddyfile from the .caddy snippets of the enabled roles, ${VARS} from .env.
render_caddyfile() {
  local out="$BOX_DIR/data/caddy/Caddyfile"
  mkdir -p "$(dirname "$out")"
  {
    echo "# generated by deploy/box — edit the roles' .caddy snippets, not this file"
    echo "{"
    echo "	email \${ACME_EMAIL}"
    echo "}"
    local role
    for role in $(role_names); do
      local s; s="$(role_file "$role" caddy)"
      [ -f "$s" ] && { echo; echo "# --- $role"; cat "$s"; } || true
    done
  } > "$out.tpl"
  # substitute ${VAR} from .env (only the vars named there; unknown ones stay, so Caddy's own {$X} survive)
  local tpl; tpl="$(cat "$out.tpl")"
  while IFS='=' read -r k v; do
    case "$k" in ''|\#*) continue ;; esac
    v="${v%\"}"; v="${v#\"}"
    tpl="${tpl//\$\{$k\}/$v}"
  done < "$BOX_DIR/.env"
  printf '%s\n' "$tpl" > "$out"
  rm -f "$out.tpl"
}

# state.json helpers (no jq dependency: the file is small and we own its shape)
state_sha() { [ -f "$BOX_DIR/state.json" ] && sed -n "s/.*\"$1\": *{[^}]*\"sha\": *\"\([0-9a-f]*\)\".*/\1/p" "$BOX_DIR/state.json" | head -1; return 0; }

write_state() {   # write_state <rolledBack:true|false> [failedRole]
  local rolled="$1" failed="${2:-}"
  {
    echo "{"
    echo "  \"updatedAt\": \"$(date -u +%FT%TZ)\","
    echo "  \"roles\": \"$ROLES\","
    echo "  \"rolledBack\": $rolled,"
    [ -n "$failed" ] && echo "  \"failedRole\": \"$failed\"," || true
    echo "  \"repos\": {"
    local first=1 name
    for name in $(repo_names); do
      local d; d="$(repo_dir "$name")"
      local sha tag
      sha="$($GIT -C "$d" rev-parse HEAD 2>/dev/null || echo unknown)"
      tag="$($GIT -C "$d" describe --tags --exact-match 2>/dev/null || echo "")"
      [ $first = 1 ] || echo ","
      first=0
      printf '    "%s": {"sha": "%s", "tag": "%s", "branch": "%s"}' "$name" "$sha" "$tag" "$(repo_branch "$name")"
    done
    echo
    echo "  }"
    echo "}"
  } > "$BOX_DIR/state.json.tmp" && mv "$BOX_DIR/state.json.tmp" "$BOX_DIR/state.json"
}

# One Telegram line when BOX_ALERT_TG_TOKEN + BOX_ALERT_TG_CHAT are set in .env; silent otherwise.
alert() {
  local token chat
  token="$(sed -n 's/^BOX_ALERT_TG_TOKEN=//p' "$BOX_DIR/.env" 2>/dev/null | tr -d '"')"
  chat="$(sed -n 's/^BOX_ALERT_TG_CHAT=//p' "$BOX_DIR/.env" 2>/dev/null | tr -d '"')"
  [ -n "$token" ] && [ -n "$chat" ] || return 0
  $CURL -sS -m 10 -o /dev/null "https://api.telegram.org/bot$token/sendMessage" \
    --data-urlencode "chat_id=$chat" --data-urlencode "text=[box $(hostname)] $*" || log "alert failed (telegram)"
}

# Run every enabled role's health script; print the first failing role, exit 1. Waits up to
# HEALTH_TIMEOUT seconds (default 60; tests set it low).
health_gate() {
  local deadline=$(( $(date +%s) + ${HEALTH_TIMEOUT:-60} ))
  local role f
  for role in $(role_names); do
    f="$(role_file "$role" health)"
    [ -x "$f" ] || continue
    until COMPOSE="$(compose_cmd)" BOX_DIR="$BOX_DIR" ROLE="$role" bash "$f" >>"$BOX_DIR/box.log" 2>&1; do
      if [ "$(date +%s)" -ge "$deadline" ]; then echo "$role"; return 1; fi
      sleep "${HEALTH_POLL:-3}"
    done
  done
  return 0
}
