/**
 * The e2e contact fixture is the app's own card, not a hand-written string.
 *
 * `e2e/support/contactCard.fixture.json` is the second person the Detox walk adds through "+ Add a bot" (a person, so
 * their thread shows Hide / "What they see" / Delete — a bot peer shows none of them). It is generated by
 * `e2e/support/makeContactCard.mjs` from a fixed seed through the app's own encoder; this pins that (1) regenerating
 * it gives exactly the committed file, and (2) the app's own reader — the prefix `addBotToGraph` routes on, then stoop's
 * `decodeContactCard` that `addContactFromQr` uses — reads it back as that person.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { makeFixtureCard, FIXTURE_NAME } from '../e2e/support/makeContactCard.mjs';
import { decodeContactCard } from '../../stoop/src/lib/contactCard.js';
import { CONTACT_CARD_PREFIX } from '../../basis/src/v2/addBot.js';

const fixture = JSON.parse(readFileSync(fileURLToPath(new URL('../e2e/support/contactCard.fixture.json', import.meta.url)), 'utf8'));

describe('the e2e contact card fixture', () => {
  it('is exactly what the generator makes from its fixed seed (nobody edits it by hand)', () => {
    const { card, uri } = makeFixtureCard();
    expect(fixture).toEqual({ name: FIXTURE_NAME, webid: card.webid, uri });
  });

  it('is read back by the app\'s own route and decoder as that person', () => {
    expect(fixture.uri.startsWith(CONTACT_CARD_PREFIX)).toBe(true);
    const card = decodeContactCard(fixture.uri.slice(CONTACT_CARD_PREFIX.length));
    expect(card).toMatchObject({ webid: fixture.webid, displayName: FIXTURE_NAME, handle: 'testa' });
  });
});
