// addressPossession.js — proving you hold the key behind an address, to the thing that routes to it.
//
// A relay's routing table maps address → socket. Until 2026-07-31 anyone could claim any address:
// `{type:'register', address}` was believed, `clients.set(address, socket)` overwrote whatever was
// there, and the rightful owner's inbound traffic went to the claimant. Content stays sealed;
// delivery and traffic analysis do not. This module is what closes that
// (`plans/DESIGN-boundary-authentication.md` §7, Decision 3).
//
// WHY IT IS THIS SMALL: an address IS a public key. `deriveCircleAddress(profileSeed, circleId)`
// returns `AgentIdentity.pubKeyFromSeed(deriveCircleSeed(…))`, and a `RelayTransport`'s primary
// address is `identity.pubKey`. So "prove you hold this address" is one signature verified against
// the address itself. Nothing is minted, stored, distributed, renewed or revoked; there is no
// admin, no group and no issuance in the loop.
//
// ── WHY THIS IS NOT `circleLink.js` ─────────────────────────────────────────────────────────────
// `circleLink.js` is the same *shape* — sign a challenge with the key behind a per-circle address,
// verify against the address — and it is deliberately NONCE-FREE, because a replay there only
// re-asserts the same identity into the same circle (idempotent, and the admin records it once).
// Registration is not idempotent in that way: a captured static signature would let anyone who ever
// saw it — including the relay operator — re-register that address on another socket or another
// relay, forever. Reusing `signCircleLinkFromSeed` here would reproduce exactly the vacuous check
// this work exists to remove. **The verifier supplies a fresh nonce; nothing else is accepted.**
//
// ── WHAT THE SIGNER IS ASKED TO SIGN ────────────────────────────────────────────────────────────
// The relay supplies a NONCE, never a message. The client builds the message itself out of the
// nonce and the address it is registering, so a hostile relay cannot use registration as a signing
// oracle for content of its choosing. The prefix is domain-separated so a signature made here can
// never be mistaken for one made anywhere else in the system.
//
// ── WHAT THIS DOES NOT COVER, STATED RATHER THAN IMPLIED ────────────────────────────────────────
// The nonce defeats CAPTURE-AND-REPLAY: a proof is useless at another relay (which issued a
// different nonce) and at another time (single-use, short-lived). It does NOT defeat a LIVE PROXY:
// a hostile relay a client is connected to can fetch a challenge from a third relay, hand it to the
// client as its own, and forward the answer — registering the client's address there. Closing that
// needs the signed message to name WHICH relay it is for, which needs a relay to have a verifiable
// identity of its own (a key, or a url it can prove). We do not have one yet; when we do, add an
// audience field here. Recorded in `plans/DECISIONS-FOR-REVIEW.md` (2026-07-31) rather than left
// for someone to discover.
import nacl from 'tweetnacl';
import { AgentIdentity } from './AgentIdentity.js';
import { deriveCircleSeed } from './circleAddress.js';
import { encode as b64encode } from '../crypto/b64.js';

/** Bytes of entropy in a registration nonce. 32 = the same order as a key; guessing is not a path. */
export const ADDRESS_NONCE_BYTES = 32;

/**
 * How long a challenge stays answerable. Long enough for a slow phone on a slow network to sign
 * and reply; short enough that a nonce sitting in a relay's memory is not a lasting object. The
 * single-use rule does the real work — this only bounds the state a connection can hold.
 */
export const ADDRESS_CHALLENGE_TTL_MS = 30_000;

/** A fresh, single-use challenge nonce (base64url). Verifier-side; never generated by a client. */
export function newAddressChallenge() {
  return b64encode(nacl.randomBytes(ADDRESS_NONCE_BYTES));
}

/**
 * The canonical message a holder signs. Binds the ADDRESS being claimed to THIS nonce, so a proof
 * cannot be lifted onto a different address or replayed against a different challenge.
 * @param {string} address
 * @param {string} nonce
 * @returns {string}
 */
export function addressPossessionMessage(address, nonce) {
  return `onderling-address-possession-v1|${String(address)}|${String(nonce)}`;
}

/**
 * Sign the challenge with an `AgentIdentity` whose `pubKey` IS the address.
 * @param {import('./AgentIdentity.js').AgentIdentity} identity
 * @param {string} address
 * @param {string} nonce
 * @returns {string} base64url Ed25519 signature
 */
export function signAddressPossession(identity, address, nonce) {
  return b64encode(identity.sign(addressPossessionMessage(address, nonce)));
}

/**
 * The signer for ONE per-circle address, vault-free — exactly as `signCircleLinkFromSeed` is. This
 * is what makes the alias case cheap: a device registering N per-circle addresses on one socket
 * signs N challenges without touching a vault N times.
 *
 * It is shaped for `Transport.addAddress(address, { sign })`: it takes the MESSAGE the adapter
 * built, not a nonce, so the caller never has to know the registration protocol — only which circle
 * the address belongs to, which is the one thing only the caller knows.
 *
 * @param {Uint8Array} profileSeed
 * @param {string} circleId
 * @returns {(message: string) => string} sign(message) → base64url Ed25519 signature
 */
export function circleAddressSigner(profileSeed, circleId) {
  const kp = nacl.sign.keyPair.fromSeed(deriveCircleSeed(profileSeed, circleId));
  return (message) => b64encode(nacl.sign.detached(new TextEncoder().encode(message), kp.secretKey));
}

/**
 * The same thing at the protocol's own level: sign THIS challenge for THIS per-circle address.
 * For callers that hold a nonce rather than a transport (another wire implementation, a test).
 * @param {Uint8Array} profileSeed
 * @param {string} circleId
 * @param {string} address  the per-circle address being registered (= `deriveCircleAddress(...)`)
 * @param {string} nonce
 * @returns {string} base64url Ed25519 signature
 */
export function signAddressPossessionFromSeed(profileSeed, circleId, address, nonce) {
  return circleAddressSigner(profileSeed, circleId)(addressPossessionMessage(address, nonce));
}

/**
 * Verify a presented proof against the address itself — deny-by-default: anything missing,
 * malformed or unparseable is `false`, never a throw the caller might treat as "unknown".
 * @param {{address?: string, nonce?: string, proof?: string}} a
 * @returns {boolean}
 */
export function verifyAddressPossession({ address, nonce, proof } = {}) {
  if (typeof address !== 'string' || !address) return false;
  if (typeof nonce   !== 'string' || !nonce)   return false;
  if (typeof proof   !== 'string' || !proof)   return false;
  try { return AgentIdentity.verify(addressPossessionMessage(address, nonce), proof, address); }
  catch { return false; }
}
