#!/usr/bin/env node
/**
 * asked-frits — the "what is Frits still being asked?" table, GENERATED from the ledger's own marker.
 *
 * A question raised mid-work and not answered is a silence, not a decision (CLAUDE.md: an idea is only
 * dropped when Frits drops it). So the open questions need to be visible in one place — but a hand-kept list
 * beside the `? Needs Frits` markers is two places for one fact, and in this repo a maintained list drifts.
 * It drifted within a day of being written: the markers said 55, the table said 4.
 *
 * So the table is a projection. The MARKER is the fact; this rewrites the block between the two comments to
 * match it. Answering a question means editing the row where the answer belongs — replacing `? Needs Frits`
 * with `✅ answered <date>` — and the table follows. Nothing is ever cleared here.
 *
 * PRIVACY: this file is tracked/public and `REMAINING-WORK.md` is not. It reads that file by a path passed in
 * or defaulted, and prints nothing from it on `--check` beyond a count — the same rule `lint-ledger.mjs`
 * follows for the same reason.
 *
 *   node scripts/asked-frits.mjs            rewrite the block in place
 *   node scripts/asked-frits.mjs --check    exit 1 if the block is stale (the guard)
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
// The roadmap is gitignored, so a test must be able to point this at a throwaway copy rather than the real
// one — a generator whose only test target is the live file is a test nobody dares run.
const FILE = process.env.ASKED_FRITS_FILE || path.join(ROOT, 'REMAINING-WORK.md');
const BEGIN = '<!-- asked-frits:begin -->';
const END = '<!-- asked-frits:end -->';

const MARKER = /\?\s*Needs Frits/;
/** `[ledger L12]` / `[ledger n/a — a product call]` — the tag the ledger guard already requires. */
const TAG = /\[ledger\s+(L\d+|n\/a)[^\]]*\]/i;
/** A date the row states for itself. Not invented when absent: a wrong date is worse than none. */
const DATE = /\b(20\d\d-\d\d-\d\d)\b/;

/**
 * One table row per marker line. Line numbers are the point: the question stays where its context is.
 *
 * THE BLOCK IS NOT SCANNED. A generated table that reads itself is not a projection, it is a feedback loop —
 * the first run rendered its own rows as new markers and the second run disagreed with the first.
 */
function rows(text) {
  const out = [];
  let inBlock = false;
  text.split('\n').forEach((line, i) => {
    if (line.includes(BEGIN)) { inBlock = true; return; }
    if (line.includes(END)) { inBlock = false; return; }
    if (inBlock) return;
    if (!MARKER.test(line)) return;
    // Three things carry the marker without being a live question, and all three are kept ON PURPOSE:
    //   · the ledger's own heading, which names the section;
    //   · a line TALKING about the practice — a brief quoting it, a lesson written up with it in quotes;
    //   · text after a `Was:`, which is how an ANSWERED row keeps its original wording for context. That one
    //     matters most: the row above it says what was decided, so counting it again reports a settled
    //     question as open, which is the same drift in the other direction.
    if (/^#+\s/.test(line.trim())) return;
    if (line.includes('asked-frits') || line.includes('`? Needs Frits`') || line.includes('"? Needs Frits')) return;
    const was = line.search(/\bWas:/);
    if (was >= 0 && line.search(MARKER) > was) return;
    const tag = (line.match(TAG)?.[1] ?? 'n/a').replace(/^l/, 'L');
    const date = line.match(DATE)?.[1] ?? '—';
    // The question itself: from the marker onward, stripped of the tag and markdown noise, one line.
    const from = line.slice(line.search(MARKER));
    const text1 = from.replace(MARKER, '').replace(TAG, '').replace(/[*_`>|]/g, '').replace(/\s+/g, ' ').trim()
      .replace(/^[—–\-:,.\s]+/, '');
    out.push({ n: i + 1, tag, date, q: text1.length > 110 ? `${text1.slice(0, 110)}…` : (text1 || '(see the row)') });
  });
  return out.reverse();   // newest first — the ledger grows downward, so the last marker is the newest
}

function render(list) {
  const head = [
    '| line | ledger | raised | the question |',
    '|---|---|---|---|',
  ];
  const body = list.map((r) => `| ${r.n} | ${r.tag} | ${r.date} | ${r.q} |`);
  return [
    BEGIN,
    `*Generated by \`node scripts/asked-frits.mjs\` from every \`? Needs Frits\` marker below — **${list.length} open**.`,
    'Do not edit this block. To ANSWER one, edit the row it lives on (replace the marker with `✅ answered <date>`),',
    'so the answer sits with its context; the table follows. Never clear a question because the work moved on.*',
    '',
    ...head,
    ...body,
    END,
  ].join('\n');
}

function main() {
  const check = process.argv.includes('--check');
  if (!existsSync(FILE)) {
    // The private roadmap is gitignored; a clone without it must not fail the aggregate.
    if (!check) console.log('asked-frits: no REMAINING-WORK.md here — nothing to project.');
    process.exit(0);
  }
  const text = readFileSync(FILE, 'utf8');
  const b = text.indexOf(BEGIN);
  const e = text.indexOf(END);
  if (b < 0 || e < 0 || e < b) {
    console.error(`\n✖ asked-frits: the ${BEGIN} / ${END} block is missing from the roadmap.`);
    console.error('  Add the two comment lines where the table belongs, then run this script.\n');
    process.exit(1);
  }
  const wanted = render(rows(text));
  const current = text.slice(b, e + END.length);
  if (current === wanted) {
    if (!check) console.log(`asked-frits: up to date (${rows(text).length} open).`);
    process.exit(0);
  }
  if (check) {
    console.error('\n✖ asked-frits: the open-questions table does not match the `? Needs Frits` markers.');
    console.error('  Run `node scripts/asked-frits.mjs` and commit. The table is generated, never hand-edited —');
    console.error('  a list maintained beside the markers drifts, which is why it is a projection.\n');
    process.exit(1);
  }
  // A FIXED POINT, not one pass. The table states LINE NUMBERS, and rewriting the block moves every line
  // below it — so a single rewrite invalidates the numbers it just wrote, and `--check` would fail on a file
  // that had only just been generated. Rewriting until the content stops changing settles that in two rounds
  // (the block's height converges as soon as the row count does); the cap is only there so a pathological
  // oscillation cannot spin.
  let out = text;
  for (let round = 0; round < 8; round += 1) {
    const bb = out.indexOf(BEGIN);
    const ee = out.indexOf(END);
    const next = out.slice(0, bb) + render(rows(out)) + out.slice(ee + END.length);
    if (next === out) break;
    out = next;
  }
  writeFileSync(FILE, out);
  console.log(`asked-frits: rewrote the table (${rows(out).length} open).`);
}

main();
